version: 0.2

env:
  variables:
    ECR_REPO: 457087769533.dkr.ecr.us-east-1.amazonaws.com/moon-aggregator-service

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR…
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_REPO
  build:
    commands:
      - echo Building the blue image…
      - docker build -t $ECR_REPO:blue .
      - echo Tagging the green image…
      - docker tag $ECR_REPO:blue $ECR_REPO:green
  post_build:
    commands:
      - echo Pushing images to ECR…
      - docker push $ECR_REPO:blue
      - docker push $ECR_REPO:green

artifacts:
  files: []
