apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification-service
    version: blue  # ← You can switch this to "green" when you want to switch traffic
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5003
  type: LoadBalancer
