apiVersion: v1
kind: Service
metadata:
  name: integration-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: integration-service
    version: green
  ports:
    - port: 5000
      targetPort: 5002
      protocol: TCP
