apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: notification-service
    version: green
  ports:
    - port: 5003
      targetPort: 5003
      protocol: TCP
