apiVersion: apps/v1
kind: Deployment
metadata:
  name: moon-agent-service-blue
  labels:
    app: moon-agent-service
    version: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moon-agent-service
      version: blue
  template:
    metadata:
      labels:
        app: moon-agent-service
        version: blue
    spec:
      containers:
        - name: moon-agent-service
          image: 457087769533.dkr.ecr.us-east-1.amazonaws.com/moon-agent-service:latest
          ports:
            - containerPort: 5000
          env:
            - name: MYSQL_HOST
              value: "mooninsurance.ca7isqgecjpt.us-east-1.rds.amazonaws.com"
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USER
              value: "admin"
            - name: MYSQL_PASSWORD
              value: "Hsnmef_9575$"
            - name: MYSQL_DB
              value: "mooninsurance_db"
